### ISSUE TITLE
OpenAPI contents inaccuracies

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-server/jupyter_server#518]
Hooray OpenAPI! Boo OpenAPI that flags as invalid the first response one's likely to generate from `/api/contents` listing a directory.

Among the offenders is `#/definitions/Content`. We probably need to have something akin to nbformat's type descriminatior, e.g. `code-cell`, `markdown-cell`.

```yaml
routes:
  properties:
    contents:
      oneOf: 
         - type: 'null'
         - '#/definitions/FileContents`
         - '#/definitions/DirectoryContents`
         - '#/definitions/NotebookContents`
         - '#/definitions/JSONContents`
```

**Comment by kevin-bates** [comment]
Hi Nick, could you please describe how you discovered this issue - mostly for my understanding?  Was this by inspection or some tooling that uncovered these issues.  I suppose this could be apparent using the [swagger editor](https://editor.swagger.io/) or similar.

I definitely see that there could be some cleanup here.  There are several instances like the following...
```yaml
content:        
    type: string        
    description: "The content, if requested (otherwise null).  Will be an array if type is 'directory'" 
format:        
    type: string        
    description: Format of content (one of null, 'text', 'base64', 'json')
```
